### ISSUE TITLE
在ubuntu环境下运行错误

### ISSUE THREAD

**Issue by ACGunion** [fffonion/xeHentai#10]
root@node4112-env-1197747:~/xeHentai# python xeHentai.py
Traceback (most recent call last):
  File "xeHentai.py", line 634, in <module>
    _print('发生错误: '),
  File "xeHentai.py", line 43, in _print
    print(convStr(str))
  File "xeHentai.py", line 69, in convStr
    return conv(str).decode('utf-8').encode(locale.getdefaultlocale()[1], errors)
TypeError: encode() argument 1 must be string, not None

**Comment by fffonion** [comment]
设置一下LANG和LC_ALL，不然含中日韩文字的图册的名字也会显示不出来
