### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by daivem** [fffonion/xeHentai#12]
直接从压缩包中第一次运行时正常（cmd窗口中提示进否要登录），解压后运行不正常，报如下错误

F:\tools\其他>xeHentai.exe
Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "D:\Dev\Python\pyinstaller-2.1\PyInstaller\loader\pyi_importers.py", line 507, in install
  File "D:\Dev\Python\pyinstaller-2.1\PyInstaller\loader\pyi_importers.py", line 156, in __init__
ImportError: Can't load frozen modules.

F:\tools\其他>

**Comment by fffonion** [comment]
目录不要包含中文

**Comment by daivem** [comment]
好的
