### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by cynosure1993** [fffonion/xeHentai#19]
可以正常登录，但开始任务后会出现如下错误信息
Exception in thread main:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "threading.py", line 754, in run
  File "xeHentai\core.py", line 272, in _task_loop
  File "xeHentai\core.py", line 197, in _do_task
KeyError: 'total'
无法完成下载，请问如何解决
版本2.0，操作系统windows10

**Comment by fffonion** [comment]
5号网站改版了，请使用2.0.0.1

**Comment by cynosure1993** [comment]
十分感谢
