### ISSUE TITLE
这个本子没法正常下载（内详）

### ISSUE THREAD

**Issue by fireattack** [fffonion/xeHentai#21]
使用方法：双击打开exe+firefox脚本下载

配置：

```
# coding:utf-8

dir = "."
download_ori = True
download_thread_cnt = 5
scan_thread_cnt = 1
proxy = None
log_path = "eh.log"
log_verbose = 3
rename_ori = True
daemon = False
rpc_interface = 'localhost'
rpc_port = 8010
rpc_secret = None
save_tasks = False
make_archive = False
```

重现步骤：

有几个bug：
1. 并没有正确重命名（正确名称应该是MJK_16_T165_001.png，结果是001.jpg…连后缀名都不对。这里顺便提一下，即使不开重命名选项，后缀也应该保持和文件格式一致）
2. 这个本下完之后软件就坏了，无法下别的（也没错误），必须重启才行

**Comment by fireattack** [comment]
Log: http://pastebin.com/ikjhpyRb

**Comment by fffonion** [comment]
OK我看看，我先把网址删了

**Comment by fireattack** [comment]
@fffonion 重命名功能好像问题很大，

1. 对于能成功重命名的，会把png重命名成jpg（例如：https://exhentai.org/g/959352/54b89d1ddd/）
2. 有些直接不能正确重命名，除了上面的还有 https://exhentai.org/g/436528/64de5ff6c3/

**Comment by fffonion** [comment]
了解√

**Comment by fffonion** [comment]
第二个问题貌似是因为设置了缩略图尺寸之后每页就不是显示40张图了……第一个问题是因为第二个问题引起的，因为一共有22张图，但是只下了20张，所以一直没完成。
2.011已修复

**Comment by fffonion** [comment]
重命名的扩展名也修好了，但是没下载完之前仍然是数字.jpg的命名，这样方便下次重新下载的时候扫描哪些已经下过了

**Comment by fireattack** [comment]
/436528/64de5ff6c3/

这本下载还是有问题，重命名的时候报错

```
DEBG - [08:42:06] 图片已下载 #021 beast_029.jpg
INFO - [08:42:06] 绅士 6R/0Z, 队列 0R/20D
VERB - [08:42:07] 绅士-down-4 GET http://45.32.246.97:6555/h/eb4d8391f27f96cba2
8984b1fe9c6e77d762acd-683767-1263-1800-jpg/keystamp=1472345400-43e2c0b6a4/beast
018.jpg 200 683767
DEBG - [08:42:07] 图片已下载 #010 beast_018.jpg
VERB - [08:42:07] t-down-4 exit
VERB - [08:42:07] t-down-2 exit
VERB - [08:42:08] t-down-5 exit
VERB - [08:42:08] t-down-3 exit
VERB - [08:42:08] t-down-1 exit
VERB - [08:42:08] t-scan-1 exit
Exception in thread monitorb3eddd57:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "xeHentai\worker.py", line 272, in run
  File "xeHentai\task.py", line 224, in rename_fname
WindowsError: [Error 183]

```

**Comment by fffonion** [comment]
这个是它本身有两个一样的文件名……我加一个(1)好了

**Comment by fffonion** [comment]
2.0.1.3已修复：）
