### ISSUE TITLE
部分作品会显示红字错误

### ISSUE THREAD

**Issue by gamania31610** [fffonion/xeHentai#35]
ERROR - [00:49:40] 任務 #7e302801 發生錯誤: Traceback (most recent call last):
  File "xeHentai\core.py", line 206, in _do_task
  File "xeHentai\worker.py", line 83, in request
  File "xeHentai\filters.py", line 49, in flt_metadata
  File "xeHentai\util\__init__.py", line 78, in htmlescape
  File "xeHentai\util\__init__.py", line 74, in replc
NameError: free variable 'unichr' referenced before assignment in enclosing scope

**Comment by fffonion** [comment]
已更新
https://dl.yooooo.us/share/xeHentai/xeHentai-2.0.1.9-%E6%B5%8B%E8%AF%95%E7%89%88.exe.zip
