### ISSUE TITLE
提示 错误

### ISSUE THREAD

**Issue by telessa** [fffonion/xeHentai#42]
[Jan 25 19:34:51] 绅士-down-1 下载图片时出错: 连接有问题？, 将在稍后重试
[Jan 25 19:34:56] 绅士-down-1 未捕获的异常
Traceback (most recent call last):
  File "xeHentai\worker.py", line 118, in run
  File "xeHentai\worker.py", line 83, in request
  File "xeHentai\filters.py", line 121, in _
  File "xeHentai\filters.py", line 171, in download_file
  File "xeHentai\core.py", line 286, in <lambda>
  File "xeHentai\task.py", line 187, in save_file
WindowsError: [Error 1392] : u'J:\\mangacon\\ehentai\\[Sano Takashi] Iketeru Futari Vol.14

**Comment by telessa** [comment]
另外一种
[Jan 25 23:30:32] 任务 #c1b013d5 下载完成
[Jan 25 23:30:32] 绅士-main GET https://exhentai.org/g/262212/ba6ec31241/ 200 30199
[Jan 25 23:30:32] 任务 #f9b44794 发生错误: Traceback (most recent call last):
  File "xeHentai\core.py", line 206, in _do_task
  File "xeHentai\worker.py", line 83, in request
  File "xeHentai\filters.py", line 50, in flt_metadata
  File "xeHentai\util\__init__.py", line 78, in htmlescape
  File "xeHentai\util\__init__.py", line 74, in replc
NameError: free variable 'unichr' referenced before assignment in enclosing scope

**Comment by fffonion** [comment]
第一个报错是ERROR_FILE_CORRUPT，建议跑一下chkdsk检查磁盘错误
第二个已经在[dev分支](https://github.com/fffonion/xeHentai/tree/dev)解决，可以下载2.0.1.9测试版 https://dl.yooooo.us/share/xeHentai/

**Comment by telessa** [comment]
非常感谢
