### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by n40355** [fffonion/xeHentai#47]
系统: Win7 (64bit)
程序: 2.0.1.9test&2.0.1.9&2.0.2.0test

點進畫廊的圖片右鍵是沒問題的，但用程式跑就會出現錯誤訊息。

3個版本下載下面這2個畫廊都會這樣
/1220915/6feae6414c/
/1221718/e3b8bcc817/

2.0.1.9的錯誤訊息
WARN - [03:23:38] 紳士-down-3 未捕獲的異常
Traceback (most recent call last):
  File "xeHentai\worker.py", line 144, in run
  File "xeHentai\worker.py", line 87, in request
  File "xeHentai\filters.py", line 121, in _
  File "xeHentai\filters.py", line 207, in download_file
  File "xeHentai\core.py", line 279, in <lambda>
  File "xeHentai\task.py", line 220, in save_file
IOError: [Errno 2] No such file or directory: u'E:\\eh2017\\xeHentai-2.0.1.9 t.exe\\Artist Archives  Guinefurrie \\003.jpg'

DEBG - [03:23:38] 紳士-down-3 下載圖片時出錯: 連接有問題？, 將在稍後重試

2.0.2.0的錯誤訊息
DEBG - [04:22:33] 紳士-down-4 下載圖片時出錯: 連接有問題？, 將在稍後重試
WARN - [04:22:34] 紳士-down-2 未捕獲的異常
Traceback (most recent call last):
  File "xeHentai\worker.py", line 193, in run
  File "xeHentai\worker.py", line 136, in request
  File "xeHentai\filters.py", line 123, in _
  File "xeHentai\filters.py", line 214, in download_file
  File "xeHentai\core.py", line 284, in <lambda>
  File "xeHentai\task.py", line 221, in save_file
IOError: [Errno 2] No such file or directory: u'E:\\eh2017\\xeHentai-2.0.2.0\\Ar
tist Archives  Guinefurrie \\.019.jpg.xeh'

可是/1220915/6feae6414c/的母畫廊/1111808/24c5055a87/是可以下載的
以為是標題有*號所以才發生錯誤，但再下載其他標題有*號的畫廊是沒問題的，就只有開頭說的那2個畫廊出現這個錯誤

另外，我重新命名是關掉的
但是重覆下載同一個畫廊時，只有JPG檔可以不重覆下載，PNG和gif檔就會又下載一次

P.S.對了上次下載到硬碟沒空間，但只跳未知的錯誤，看大大看要不要在錯誤訊息裡多個空間不足的項目

**Comment by n40355** [comment]
剛剛發現這個要下載這個畫廊/231380/9bb3e6596c/也有一樣的問題

**Comment by fffonion** [comment]
已于2.020正式版中解决，如仍有问题，请重新打开本issue
