### ISSUE TITLE
下载卡住及其他可能存在的图片下载错误

### ISSUE THREAD

**Issue by telessa** [fffonion/xeHentai#71]
有使用代理 但是频繁出现类似的错误

[Oct 29 22:22:01] 任务 #e688e234 开始
[Oct 29 22:22:01] 任务 #e688e234 发生错误: Traceback (most recent call last):
  File "xeHentai\core.py", line 203, in _do_task
  File "xeHentai\worker.py", line 92, in request
  File "xeHentai\proxy.py", line 38, in proxied_request
PoolException: try to use proxy but no proxies avaliable

[Oct 29 22:22:01] 任务 #3de7354b 开始
[Oct 29 22:22:01] 任务 #3de7354b 发生错误: Traceback (most recent call last):
  File "xeHentai\core.py", line 203, in _do_task
  File "xeHentai\worker.py", line 92, in request
  File "xeHentai\proxy.py", line 38, in proxied_request
PoolException: try to use proxy but no proxies avaliable

[Oct 29 22:22:01] 任务 #094d5765 开始
[Oct 29 22:22:01] 任务 #094d5765 发生错误: Traceback (most recent call last):
  File "xeHentai\core.py", line 203, in _do_task
  File "xeHentai\worker.py", line 92, in request
  File "xeHentai\proxy.py", line 38, in proxied_request
PoolException: try to use proxy but no proxies avaliable

[Oct 29 22:22:01] 任务 #78dbb420 开始
[Oct 29 22:22:01] 任务 #78dbb420 发生错误: Traceback (most recent call last):
  File "xeHentai\core.py", line 203, in _do_task
  File "xeHentai\worker.py", line 92, in request
  File "xeHentai\proxy.py", line 38, in proxied_request
PoolException: try to use proxy but no proxies avaliable

[Oct 29 22:22:01] 任务 #a706e51e 开始
[Oct 29 22:22:01] 任务 #a706e51e 发生错误: Traceback (most recent call last):
  File "xeHentai\core.py", line 203, in _do_task
  File "xeHentai\worker.py", line 92, in request
  File "xeHentai\proxy.py", line 38, in proxied_request
PoolException: try to use proxy but no proxies avaliable

[Oct 29 22:22:05] 绅士 5R/0Z, 队列 0R/0D
[Oct 29 22:22:10] 绅士 5R/0Z, 队列 0R/0D
[Oct 29 22:22:16] 绅士 5R/0Z, 队列 0R/0D
[Oct 29 22:22:21] 绅士 5R/0Z, 队列 0R/0D
[Oct 29 22:22:26] 绅士 5R/0Z, 队列 0R/0D
[Oct 29 22:22:31] 绅士 5R/0Z, 队列 0R/0D
[Oct 29 22:22:36] 绅士 5R/0Z, 队列 0R/0D
[Oct 29 22:22:42] 绅士 5R/0Z, 队列 0R/0D
[Oct 29 22:22:47] 绅士 5R/0Z, 队列 0R/0D
[Oct 29 22:22:52] 绅士 5R/0Z, 队列 0R/0D
[Oct 29 22:22:57] 绅士 5R/0Z, 队列 0R/0D
[Oct 29 22:23:03] 绅士 5R/0Z, 队列 0R/0D
[Oct 29 22:23:08] 绅士 5R/0Z, 队列 0R/0D
[Oct 29 22:23:13] 绅士 5R/0Z, 队列 0R/0D
[Oct 29 22:23:18] 绅士 5R/0Z, 队列 0R/0D
[Oct 29 22:23:23] 绅士 5R/0Z, 队列 0R/0D
[Oct 29 22:23:29] 绅士 5R/0Z, 队列 0R/0D
[Oct 29 22:23:34] 绅士 5R/0Z, 队列 0R/0D
[Oct 29 22:23:39] 绅士 5R/0Z, 队列 0R/0D
[Oct 29 22:23:39] 任务 #f9918683 卡住了, 可能是脚本有bug, 或者网络连接太慢了
[Oct 29 22:38:48] xeHentai 2.021-dev 已启动

这个提示代理错误 但是不切换节点 重试也没有代理出错提示

[Oct 29 23:04:50] 绅士-down-3 已下载图片 #185 Senpai_by_Iori_Yuzuru_186.jpg
[Oct 29 23:04:50] 绅士 6R/0Z, 队列 0R/185D
[Oct 29 23:04:51] 绅士-down-2 已下载图片 #186 Senpai_by_Iori_Yuzuru_187.jpg
[Oct 29 23:04:55] 绅士 6R/0Z, 队列 0R/186D
[Oct 29 23:05:01] 绅士 6R/0Z, 队列 0R/186D
[Oct 29 23:05:06] 绅士 6R/0Z, 队列 0R/186D
[Oct 29 23:05:11] 绅士 6R/0Z, 队列 0R/186D
[Oct 29 23:05:16] 绅士 6R/0Z, 队列 0R/186D
[Oct 29 23:05:21] 绅士 6R/0Z, 队列 0R/186D
[Oct 29 23:05:27] 绅士 6R/0Z, 队列 0R/186D
[Oct 29 23:05:32] 绅士 6R/0Z, 队列 0R/186D
[Oct 29 23:05:37] 绅士 6R/0Z, 队列 0R/186D
[Oct 29 23:05:42] 绅士 6R/0Z, 队列 0R/186D
[Oct 29 23:05:47] 绅士 6R/0Z, 队列 0R/186D
[Oct 29 23:05:52] 绅士 6R/0Z, 队列 0R/186D
[Oct 29 23:05:58] 绅士 6R/0Z, 队列 0R/186D
[Oct 29 23:06:03] 绅士 6R/0Z, 队列 0R/186D
[Oct 29 23:06:08] 绅士 6R/0Z, 队列 0R/186D
[Oct 29 23:06:13] 绅士 6R/0Z, 队列 0R/186D
[Oct 29 23:06:18] 绅士 6R/0Z, 队列 0R/186D
[Oct 29 23:06:23] 绅士 6R/0Z, 队列 0R/186D
[Oct 29 23:06:29] 绅士 6R/0Z, 队列 0R/186D
[Oct 29 23:06:29] 任务 #9cb51ecc 卡住了, 可能是脚本有bug, 或者网络连接太慢了
[Oct 29 23:06:43] xeHentai 2.021-dev 已启动

这种也很频繁 日志里有12次 只能手动重启

[Oct 29 17:49:56] 任务 #f282f1b5 将下载73个文件，共73个 
[Oct 29 17:49:56] t-scan-1 start
[Oct 29 17:49:56] wait 5 threads in state 10
[Oct 29 17:49:57] 绅士-down-1 未捕获的异常
Traceback (most recent call last):
  File "xeHentai\worker.py", line 195, in run
  File "xeHentai\worker.py", line 136, in request
  File "xeHentai\filters.py", line 150, in _
  File "xeHentai\filters.py", line 241, in download_file
  File "xeHentai\core.py", line 293, in <lambda>
  File "xeHentai\task.py", line 279, in get_fname
KeyError: u'http://98.27.149.42:2345/h/e28f0883a970c6d89a071274086857eeda6c52b8-294481-983-1400-jpg/keystamp=1572342900-26706e2fd6;fileindex=21563738;xres=org/P_214.jpg'

[Nov 09 10:36:45] 绅士-down-7 未捕获的异常
Traceback (most recent call last):
  File "xeHentai\worker.py", line 195, in run
  File "xeHentai\worker.py", line 136, in request
  File "xeHentai\filters.py", line 150, in _
  File "xeHentai\filters.py", line 241, in download_file
  File "xeHentai\core.py", line 293, in <lambda>
  File "xeHentai\task.py", line 279, in get_fname
KeyError: u'http://112.185.119.204:51723/h/ca9ba4a2fafba0c4893e97d5da1609364e437a8d-411101-970-1400-jpg/keystamp=1573267500-a1cd4f2d1d;fileindex=20749530;xres=org/143.jpg'

这种也是频繁出现 会提示worker.py 然后会跳过下载下一个任务 或者一张图 并不会卡住

手动重启重下有时会下载一百多张图片中的几张 或者任务的全部图片 
但是手动检查已下载图片 重下的图片文件创建时间与重启时间一致 但并不是错误提示的图片
错误提示的图 已经在错误提示的时间点 下载完成 而且没有出错

这样的错误到底是漏下的 还是别的？
日志太大 notepad 容易假死 这类错误没有仔细验证的 只看了其中两个任务

**Comment by fffonion** [comment]
2.022已修复，可至release或https://dl.yooooo.us/share/xeHentai/ 下载尝试
