### ISSUE TITLE
未捕获的异常

### ISSUE THREAD

**Issue by wialny** [fffonion/xeHentai#77]
`WARN - 绅士-scan-1 未捕获的异常
Traceback (most recent call last):
  File "xeHentai\worker.py", line 239, in run
  File "xeHentai\worker.py", line 136, in request
  File "xeHentai\filters.py", line 159, in _
  File "xeHentai\filters.py", line 211, in flt_imgurl
  File "xeHentai\core.py", line 272, in <lambda>
  File "xeHentai\task.py", line 125, in put_img_queue
  File "xeHentai\task.py", line 305, in get_imghash
IndexError: list index out of range

WARN -  scan-1 扫描页面 xxxx  失败: 1009`

貌似是因为下载速度不到10K/s重试次数过多而造成的. 
猜测可能是当前ip短时间内连接过多(下载有超过1000页), 换ip后就好了

**Comment by dadeshuo** [comment]
同样出现这个问题，出现这个问题后整个下载器好像就卡死一样

**Comment by wialny** [comment]
我是把速度改成了5K/s

不过现在会也开完了, 纪念日也过完了, 连线品质早已恢复稳定

dadeshuo <notifications@github.com> 於 2020年7月3日 週五 下午9:36寫道：
