### ISSUE TITLE
突然下载不了

### ISSUE THREAD

**Issue by yumo137** [fffonion/xeHentai#85]
无论是RPC模式还是点我开始，都是现实下面的文字：

WARN - [16:11:24] scan-1 扫描页面 https://exhentai.org/s/7f60afe0bb/1305585-25 失败: 1009
WARN - [16:11:25] 绅士-scan-1 未捕获的异常
Traceback (most recent call last):
  File "xeHentai\worker.py", line 239, in run
  File "xeHentai\worker.py", line 136, in request
  File "xeHentai\filters.py", line 159, in _
  File "xeHentai\filters.py", line 211, in flt_imgurl
  File "xeHentai\core.py", line 272, in <lambda>
  File "xeHentai\task.py", line 125, in put_img_queue
  File "xeHentai\task.py", line 305, in get_imghash
IndexError: list index out of range

另外RPC模式在eh主界面那个可以多选的小方框也没了，没法直接在浏览页批量选择下载。
是因为最近eh改变了什么设置吗

**Comment by yumo137** [comment]
试了下原来是e站最近不挂代理进不去，而挂了代理下载就会出问题跳黄字，关了代理就能正常下载了。
但是不挂代理也浏览不了e站，RPC的主界面批量下载没了也怪可惜的。
我的代理是用的V2ray，不过RPC设置里的代理应该设置成什么没研究懂。
如果可以希望能帮忙解答下该怎么操作~

**Comment by fffonion** [comment]
@yumo137 打开本地的v2ray之后，设置
```python
proxy = ['socks5h://127.0.0.1:XXXX‘]
```
其中`XXXX`是v2ray本地端口
