### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by adern9** [fffonion/xeHentai#95]
https://exhentai.org/g/1283918/1ae7835b3f/#
https://exhentai.org/g/1643021/6dc1d546d9/#
https://exhentai.org/g/2232697/d6480df659/#

用xeHentai下載上述連結時，均會出現下列錯誤訊息

```
DEBG - [01:51:00] 更新渠道為: 正式版
INFO - [01:51:00] xeHentai 2.023-cab811e(2.023) 已啟動
INFO - [01:51:00] RPC伺服器監聽在 localhost:8010
INFO - [01:51:00] WebUI 地址為 http://localhost:8010/ui/#host=localhost,port=8010,https=no 或者 https://xehentai.yooooo
DEBG - [01:51:01] 沒有可用更新
INFO - [01:52:09] 任務 #6ddd4bbb 開始
INFO - [01:52:13] 任務 #6ddd4bbb 標題 (C94) [奈工房 ()] 淫?特異?英?風俗七番勝負 (Fate/Grand Order) [中?翻?]
INFO - [01:52:13] 任務 #6ddd4bbb 將下載27個文件，共27個
WARN - [01:52:14] RPC: can't find 000.jpg
WARN - [01:52:15] 紳士-down-1 未捕獲的異常
Traceback (most recent call last):
  File "xeHentai\worker.py", line 239, in run
  File "xeHentai\worker.py", line 136, in request
  File "xeHentai\filters.py", line 159, in _
  File "xeHentai\filters.py", line 250, in download_file
  File "xeHentai\core.py", line 299, in <lambda>
  File "xeHentai\task.py", line 227, in save_file
  File "xeHentai\task.py", line 305, in get_imghash
IndexError: list index out of range

Exception in thread down-1:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "xeHentai\worker.py", line 252, in run
  File "xeHentai\filters.py", line 142, in _
  File "xeHentai\core.py", line 304, in <lambda>
  File "xeHentai\task.py", line 305, in get_imghash
IndexError: list index out of range

INFO - [01:52:17] 紳士 2R/0Z, 隊列 6R/0D, 0 B/s
INFO - [01:52:22] 紳士 2R/0Z, 隊列 18R/0D, 0 B/s
INFO - [01:52:27] 紳士 2R/0Z, 隊列 26R/0D, 0 B/s
INFO - [01:52:33] 紳士 2R/0Z, 隊列 26R/0D, 0 B/s
INFO - [01:52:38] 紳士 2R/0Z, 隊列 26R/0D, 0 B/s
INFO - [01:52:43] 紳士 2R/0Z, 隊列 26R/0D, 0 B/s
INFO - [01:52:48] 紳士 2R/0Z, 隊列 26R/0D, 0 B/s
INFO - [01:52:53] 紳士 2R/0Z, 隊列 26R/0D, 0 B/s
WARN - [01:52:54] 紳士-down-1 掛了, 不再理它
INFO - [01:52:58] 紳士 1R/0Z, 隊列 26R/0D, 0 B/s
INFO - [01:53:03] 紳士 1R/0Z, 隊列 26R/0D, 0 B/s
INFO - [01:53:08] 紳士 1R/0Z, 隊列 26R/0D, 0 B/s
INFO - [01:53:13] 紳士 1R/0Z, 隊列 26R/0D, 0 B/s
INFO - [01:53:18] 紳士 1R/0Z, 隊列 26R/0D, 0 B/s
INFO - [01:53:23] 紳士 1R/0Z, 隊列 26R/0D, 0 B/s
INFO - [01:53:28] 紳士 1R/0Z, 隊列 26R/0D, 0 B/s
INFO - [01:53:33] 紳士 1R/0Z, 隊列 26R/0D, 0 B/s
INFO - [01:53:38] 紳士 1R/0Z, 隊列 26R/0D, 0 B/s
INFO - [01:53:43] 紳士 1R/0Z, 隊列 26R/0D, 0 B/s
INFO - [01:53:48] 紳士 1R/0Z, 隊列 26R/0D, 0 B/s
INFO - [01:53:48] 任務 #6ddd4bbb 剩餘以下圖片未下載: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19
, 20, 21, 22, 23, 24, 25, 26]
WARN - [01:53:48] 任務 #6ddd4bbb 卡住了, 可能是腳本有bug, 或者網絡連接太慢了
```

但後來用
https://exhentai.org/g/2431458/9fa24a256f/#
測試下載，卻不會出錯，請問是我什麼地方設定錯了嗎？

**Comment by fffonion** [comment]
这个现在修复了，可以更新试试！
