### ISSUE TITLE
2.0.2.3 RPC 报错

### ISSUE THREAD

**Issue by ryanlo713** [fffonion/xeHentai#98]
```
DEBG - [17:34:04] 更新渠道为: 正式版
INFO - [17:34:04] xeHentai 2.023-de36e5e(2.023) 已启动
INFO - [17:34:04] RPC服务器监听在 localhost:8010
DEBG - [17:34:05] 没有可用更新
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 56434)
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 536, in _make_request
  File "urllib3\connection.py", line 507, in getresponse
  File "http\client.py", line 1395, in getresponse
  File "http\client.py", line 325, in begin
  File "http\client.py", line 294, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 843, in urlopen
  File "urllib3\util\retry.py", line 474, in increment
  File "urllib3\util\util.py", line 38, in reraise
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 536, in _make_request
  File "urllib3\connection.py", line 507, in getresponse
  File "http\client.py", line 1395, in getresponse
  File "http\client.py", line 325, in begin
  File "http\client.py", line 294, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 272, in do_GET
    r = self.http.get("http://xehentai.yooooo.us%s?_=%d" %(path, time.time()),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "requests\sessions.py", line 602, in get
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 682, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "socketserver.py", line 691, in process_request_thread
  File "socketserver.py", line 361, in finish_request
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 52, in <lambda>
    self.server = ThreadedHTTPServer(self.bind_addr, lambda *x: Handler(self.xeH, self.secret, *x))
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 158, in __init__
    BaseHTTPRequestHandler.__init__(self, *args)
  File "socketserver.py", line 755, in __init__
  File "http\server.py", line 436, in handle
  File "http\server.py", line 424, in handle_one_request
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 129, in f
    func(self)
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 275, in do_GET
    self.xeH.logger.warn("error pulling %s from remote server: %s" % (path, err))
                                                                            ^^^
NameError: name 'err' is not defined
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 56437)
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 536, in _make_request
  File "urllib3\connection.py", line 507, in getresponse
  File "http\client.py", line 1395, in getresponse
  File "http\client.py", line 325, in begin
  File "http\client.py", line 294, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 843, in urlopen
  File "urllib3\util\retry.py", line 474, in increment
  File "urllib3\util\util.py", line 38, in reraise
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 536, in _make_request
  File "urllib3\connection.py", line 507, in getresponse
  File "http\client.py", line 1395, in getresponse
  File "http\client.py", line 325, in begin
  File "http\client.py", line 294, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 272, in do_GET
    r = self.http.get("http://xehentai.yooooo.us%s?_=%d" %(path, time.time()),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "requests\sessions.py", line 602, in get
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 682, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "socketserver.py", line 691, in process_request_thread
  File "socketserver.py", line 361, in finish_request
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 52, in <lambda>
    self.server = ThreadedHTTPServer(self.bind_addr, lambda *x: Handler(self.xeH, self.secret, *x))
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 158, in __init__
    BaseHTTPRequestHandler.__init__(self, *args)
  File "socketserver.py", line 755, in __init__
  File "http\server.py", line 436, in handle
  File "http\server.py", line 424, in handle_one_request
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 129, in f
    func(self)
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 275, in do_GET
    self.xeH.logger.warn("error pulling %s from remote server: %s" % (path, err))
                                                                            ^^^
NameError: name 'err' is not defined
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 56443)
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 536, in _make_request
  File "urllib3\connection.py", line 507, in getresponse
  File "http\client.py", line 1395, in getresponse
  File "http\client.py", line 325, in begin
  File "http\client.py", line 294, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 843, in urlopen
  File "urllib3\util\retry.py", line 474, in increment
  File "urllib3\util\util.py", line 38, in reraise
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 536, in _make_request
  File "urllib3\connection.py", line 507, in getresponse
  File "http\client.py", line 1395, in getresponse
  File "http\client.py", line 325, in begin
  File "http\client.py", line 294, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 272, in do_GET
    r = self.http.get("http://xehentai.yooooo.us%s?_=%d" %(path, time.time()),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "requests\sessions.py", line 602, in get
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 682, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "socketserver.py", line 691, in process_request_thread
  File "socketserver.py", line 361, in finish_request
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 52, in <lambda>
    self.server = ThreadedHTTPServer(self.bind_addr, lambda *x: Handler(self.xeH, self.secret, *x))
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 158, in __init__
    BaseHTTPRequestHandler.__init__(self, *args)
  File "socketserver.py", line 755, in __init__
  File "http\server.py", line 436, in handle
  File "http\server.py", line 424, in handle_one_request
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 129, in f
    func(self)
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 275, in do_GET
    self.xeH.logger.warn("error pulling %s from remote server: %s" % (path, err))
                                                                            ^^^
NameError: name 'err' is not defined
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 56445)
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 536, in _make_request
  File "urllib3\connection.py", line 507, in getresponse
  File "http\client.py", line 1395, in getresponse
  File "http\client.py", line 325, in begin
  File "http\client.py", line 294, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 843, in urlopen
  File "urllib3\util\retry.py", line 474, in increment
  File "urllib3\util\util.py", line 38, in reraise
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 536, in _make_request
  File "urllib3\connection.py", line 507, in getresponse
  File "http\client.py", line 1395, in getresponse
  File "http\client.py", line 325, in begin
  File "http\client.py", line 294, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 272, in do_GET
    r = self.http.get("http://xehentai.yooooo.us%s?_=%d" %(path, time.time()),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "requests\sessions.py", line 602, in get
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 682, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "socketserver.py", line 691, in process_request_thread
  File "socketserver.py", line 361, in finish_request
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 52, in <lambda>
    self.server = ThreadedHTTPServer(self.bind_addr, lambda *x: Handler(self.xeH, self.secret, *x))
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 158, in __init__
    BaseHTTPRequestHandler.__init__(self, *args)
  File "socketserver.py", line 755, in __init__
  File "http\server.py", line 436, in handle
  File "http\server.py", line 424, in handle_one_request
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 129, in f
    func(self)
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 275, in do_GET
    self.xeH.logger.warn("error pulling %s from remote server: %s" % (path, err))
                                                                            ^^^
NameError: name 'err' is not defined
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 56452)
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 536, in _make_request
  File "urllib3\connection.py", line 507, in getresponse
  File "http\client.py", line 1395, in getresponse
  File "http\client.py", line 325, in begin
  File "http\client.py", line 294, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 843, in urlopen
  File "urllib3\util\retry.py", line 474, in increment
  File "urllib3\util\util.py", line 38, in reraise
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 536, in _make_request
  File "urllib3\connection.py", line 507, in getresponse
  File "http\client.py", line 1395, in getresponse
  File "http\client.py", line 325, in begin
  File "http\client.py", line 294, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 272, in do_GET
    r = self.http.get("http://xehentai.yooooo.us%s?_=%d" %(path, time.time()),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "requests\sessions.py", line 602, in get
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 682, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "socketserver.py", line 691, in process_request_thread
  File "socketserver.py", line 361, in finish_request
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 52, in <lambda>
    self.server = ThreadedHTTPServer(self.bind_addr, lambda *x: Handler(self.xeH, self.secret, *x))
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 158, in __init__
    BaseHTTPRequestHandler.__init__(self, *args)
  File "socketserver.py", line 755, in __init__
  File "http\server.py", line 436, in handle
  File "http\server.py", line 424, in handle_one_request
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 129, in f
    func(self)
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 275, in do_GET
    self.xeH.logger.warn("error pulling %s from remote server: %s" % (path, err))
                                                                            ^^^
NameError: name 'err' is not defined
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 56454)
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 536, in _make_request
  File "urllib3\connection.py", line 507, in getresponse
  File "http\client.py", line 1395, in getresponse
  File "http\client.py", line 325, in begin
  File "http\client.py", line 294, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 843, in urlopen
  File "urllib3\util\retry.py", line 474, in increment
  File "urllib3\util\util.py", line 38, in reraise
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 536, in _make_request
  File "urllib3\connection.py", line 507, in getresponse
  File "http\client.py", line 1395, in getresponse
  File "http\client.py", line 325, in begin
  File "http\client.py", line 294, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 272, in do_GET
    r = self.http.get("http://xehentai.yooooo.us%s?_=%d" %(path, time.time()),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "requests\sessions.py", line 602, in get
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 682, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "socketserver.py", line 691, in process_request_thread
  File "socketserver.py", line 361, in finish_request
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 52, in <lambda>
    self.server = ThreadedHTTPServer(self.bind_addr, lambda *x: Handler(self.xeH, self.secret, *x))
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 158, in __init__
    BaseHTTPRequestHandler.__init__(self, *args)
  File "socketserver.py", line 755, in __init__
  File "http\server.py", line 436, in handle
  File "http\server.py", line 424, in handle_one_request
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 129, in f
    func(self)
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 275, in do_GET
    self.xeH.logger.warn("error pulling %s from remote server: %s" % (path, err))
                                                                            ^^^
NameError: name 'err' is not defined
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 56494)
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 536, in _make_request
  File "urllib3\connection.py", line 507, in getresponse
  File "http\client.py", line 1395, in getresponse
  File "http\client.py", line 325, in begin
  File "http\client.py", line 294, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 843, in urlopen
  File "urllib3\util\retry.py", line 474, in increment
  File "urllib3\util\util.py", line 38, in reraise
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 536, in _make_request
  File "urllib3\connection.py", line 507, in getresponse
  File "http\client.py", line 1395, in getresponse
  File "http\client.py", line 325, in begin
  File "http\client.py", line 294, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 272, in do_GET
    r = self.http.get("http://xehentai.yooooo.us%s?_=%d" %(path, time.time()),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "requests\sessions.py", line 602, in get
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 682, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "socketserver.py", line 691, in process_request_thread
  File "socketserver.py", line 361, in finish_request
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 52, in <lambda>
    self.server = ThreadedHTTPServer(self.bind_addr, lambda *x: Handler(self.xeH, self.secret, *x))
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 158, in __init__
    BaseHTTPRequestHandler.__init__(self, *args)
  File "socketserver.py", line 755, in __init__
  File "http\server.py", line 436, in handle
  File "http\server.py", line 424, in handle_one_request
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 129, in f
    func(self)
  File "C:\xeHentai\src.zip\xeHentai\rpc.py", line 275, in do_GET
    self.xeH.logger.warn("error pulling %s from remote server: %s" % (path, err))
                                                                            ^^^
NameError: name 'err' is not defined
----------------------------------------
```
--------------------
另外 `RPC模式.bat`有一些问题，修正如下
```
@echo off
cd /d %~dp0
xeHentai-2.0.2.3.exe --rpc-port=8010
pause
```

**Comment by fffonion** [comment]
感谢反馈，已经修复，请使用更新功能获取修复：）
